spring.application.name=backend

# 1. 数据库连接（连接你新建的 finance_db）
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/finance_db}
spring.datasource.username=${DB_USERNAME:shiqing}
spring.datasource.password=${DB_PASSWORD}

# 2. JPA / Hibernate 配置
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=local
